flux_path: "/root/autodl-tmp/FLUX.1-dev"
dit_path: "/root/autodl-tmp/Step1X-Edit/step1x-edit-i1258.safetensors"
ae_path: "/root/autodl-tmp/Step1X-Edit/vae.safetensors"
qwen2vl_model_path: "/root/autodl-tmp/Qwen2.5-VL-7B-Instruct"

dtype: "bfloat16"

model:
  union_cond_attn: true
  add_cond_attn: false
  latent_lora: false

train:
  batch_size: 1
  accumulate_grad_batches: 4
  dataloader_workers: 5
  save_interval: 500
  sample_interval: 250
  max_steps: -1
  gradient_checkpointing: true
  save_path: "/root/autodl-tmp/runs"

  condition_type: "metaquery"
  dataset:
    data_json: ["/root/autodl-tmp/flux_short.json","/root/autodl-tmp/mmd_data_processed_skipped.json", "/root/autodl-tmp/pinterest_data_processed_shorter.json"]
    image_dir: "/root/autodl-tmp/data_flux_mmd"
    image_size: 512
    target_size: 512
  wandb:
    project: "Step1X-Edit"

  lora_config:
    r: 8
    lora_alpha: 8
    init_lora_weights: "gaussian"
    target_modules: "(.*img_in|.*double_blocks\\.[0-9]+\\.img_mod\\.lin|.*double_blocks\\.[0-9]+\\.img_attn\\.qkv|.*double_blocks\\.[0-9]+\\.img_attn\\.proj|.*double_blocks\\.[0-9]+\\.img_mlp\\.2|.*single_bloks\\.[0-9]+\\.modulation\\.lin|.*single_bloks\\.[0-9]+\\.linear1|.*single_bloks\\.[0-9]+\\.linear2)"
  optimizer:
    type: "Prodigy"
    params:
      lr: 1
      use_bias_correction: true
      safeguard_warmup: true
      weight_decay: 0.01
  ae_params:
    resolution: 256
    in_channels: 3
    ch: 128
    out_ch: 3
    ch_mult: [1, 2, 4, 4]
    num_res_blocks: 2
    z_channels: 16
    scale_factor: 0.3611
    shift_factor: 0.1159
  qwen2_params:
    model_path: "/root/autodl-tmp/Qwen2.5-VL-7B-Instruct"
    max_length: 1280